"use client";

import Link from "next/link";
import Image from "next/image";
import { useSyncExternalStore } from "react";
import { useSiteContent } from "@/components/content-provider";
import { ActionButton, SiteFooter, SiteHeader } from "@/components/site-shell";
import { Eyebrow, SectionTitle, VisualPlaceholder } from "@/components/home-sections";

const trust = ["Family-Owned & Operated", "Licensed & Insured", "Same-Day Service Available", "Residential & Commercial", "Professional HVAC Service", "South Florida Local Service"];
const strengths = ["Family-Owned & Operated", "Licensed & Insured", "Honest Recommendations", "Clear Communication", "Professional Workmanship", "Respect for Your Property", "Residential & Commercial Service", "Local South Florida Company"];
function useReducedMotion() { return useSyncExternalStore((notify) => { const media = window.matchMedia("(prefers-reduced-motion: reduce)"); media.addEventListener("change", notify); return () => media.removeEventListener("change", notify); }, () => window.matchMedia("(prefers-reduced-motion: reduce)").matches, () => false); }
function AcServicesHeroMedia({ video, poster, settings }: { video: string; poster: string; settings: { fit: "cover" | "contain"; position: "center" | "left" | "right"; autoplay: boolean; loop: boolean; controls: boolean } }) {
	const reducedMotion = useReducedMotion();
	const mediaClass = `absolute inset-0 size-full ${settings.fit === "contain" ? "object-contain" : "object-cover"} ${settings.position === "left" ? "object-left" : settings.position === "right" ? "object-right" : "object-center"}`;
	return <div className="relative mt-10 aspect-video overflow-hidden rounded-xl border border-sky-300/30 bg-[#061c32] shadow-2xl sm:mt-12"><VisualPlaceholder label="AC SERVICES HERO VIDEO" className="absolute inset-0 size-full" />{reducedMotion ? <Image src={poster} alt="Top Notch AC Services technician performing an air conditioning diagnostic in South Florida" fill sizes="(min-width: 1280px) 1280px, 100vw" className={mediaClass} /> : <video className={mediaClass} autoPlay={settings.autoplay} muted loop={settings.loop} playsInline controls={settings.controls} poster={poster}><source src={video} type="video/mp4" /></video>}<div className="pointer-events-none absolute inset-0 bg-gradient-to-t from-[#082544]/35 via-transparent to-transparent" /></div>;
}

export default function AcServicesPage() {
	const content = useSiteContent();
	const ac = content.acHub;
	const priorityAreas = content.serviceAreas.filter((area) => area.enabled && area.priority);
	return <><SiteHeader /><main className="overflow-hidden bg-white text-slate-900">
		<script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ "@context": "https://schema.org", "@type": "HVACBusiness", name: content.companyName, telephone: content.phone, areaServed: priorityAreas.map((area) => ({ "@type": "City", name: area.name })), makesOffer: ac.serviceCards.map((service) => ({ "@type": "Offer", itemOffered: { "@type": "Service", name: service.title } })) }) }} />
		<section className="bg-[#082544] py-16 text-white sm:py-24"><div className="mx-auto max-w-7xl px-5 text-center lg:px-8"><Eyebrow light>TOP NOTCH AC SERVICES</Eyebrow><h1 className="mx-auto mt-4 max-w-4xl text-4xl font-black leading-tight sm:text-5xl">{ac.heroTitle}</h1><p className="mx-auto mt-5 max-w-3xl text-lg leading-8 text-sky-100">{ac.heroDescription}</p><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><ActionButton phone>{content.ctas.primary}</ActionButton><ActionButton light>{content.ctas.secondary}</ActionButton></div><p className="mt-7 text-base font-extrabold">Licensed & Insured <span className="mx-2 text-sky-300">|</span> Florida HVAC License {content.license}</p><AcServicesHeroMedia video={ac.heroVideo} poster={ac.heroPoster} settings={ac.heroMedia} /></div></section>
		<section className="border-b border-sky-100 bg-sky-50"><div className="mx-auto grid max-w-7xl divide-y divide-sky-200 px-5 sm:grid-cols-2 sm:divide-x sm:divide-y-0 lg:grid-cols-6 lg:px-8">{trust.map((item) => <p key={item} className="py-5 text-center text-sm font-extrabold text-[#082544]">{item}</p>)}</div></section>
		<section className="mx-auto max-w-7xl px-5 py-16 sm:px-8 sm:py-24"><SectionTitle eyebrow="AC TROUBLESHOOTING" title="Having AC Problems?" text="If your air conditioner is not cooling properly, will not turn on, is leaking water, making unusual noises or cycling too often, our technicians can inspect the system and determine the cause." /><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{ac.problems.map((problem) => <Link key={problem} href="/ac-repair" className="rounded-xl border border-slate-200 bg-white p-5 text-sm font-bold text-[#082544] transition hover:-translate-y-0.5 hover:border-sky-400 hover:shadow-sm focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-sky-500">{problem}<span className="mt-4 block text-sky-600">Schedule a diagnostic +</span></Link>)}</div><div className="mt-8"><ActionButton href="/ac-repair">Schedule AC Diagnostic</ActionButton></div></section>
		<section className="bg-[#eef7fb] py-16 sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-8"><SectionTitle eyebrow="OUR AC SERVICES" title="Complete Air Conditioning Services" text="One local company for system repairs, installation, maintenance and comfort solutions." /><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{ac.serviceCards.map((service) => <Link key={service.title} href={service.href} className="group rounded-xl border border-slate-200 bg-white p-6 transition hover:-translate-y-1 hover:border-sky-400 hover:shadow-lg focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-sky-500"><h3 className="text-xl font-black text-[#082544]">{service.title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{service.description}</p><span className="mt-6 block text-sm font-bold text-sky-700">Explore service +</span></Link>)}</div></div></section>
		<section className="mx-auto max-w-7xl px-5 py-16 sm:px-8 sm:py-24"><SectionTitle eyebrow="COMMON AC REPAIRS" title="Common AC Repairs We Handle" /><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{ac.repairs.map((repair) => <p key={repair} className="rounded-lg border border-slate-200 px-4 py-4 text-sm font-bold text-[#082544]">{repair}</p>)}</div></section>
		<section className="bg-[#082544] py-16 text-white sm:py-24"><div className="mx-auto grid max-w-7xl gap-10 px-5 lg:grid-cols-[.85fr_1.15fr] lg:px-8"><VisualPlaceholder label="COMPLETE AC DIAGNOSTIC" className="min-h-80 rounded-xl border border-white/15" /><div><Eyebrow light>PROFESSIONAL DIAGNOSTICS</Eyebrow><h2 className="mt-3 text-3xl font-black sm:text-4xl">What We Check During an AC Diagnostic</h2><div className="mt-7 grid grid-cols-2 gap-3">{ac.diagnostics.map((item) => <p key={item} className="border-b border-white/15 py-3 text-sm font-bold">{item}</p>)}</div><p className="mt-7 max-w-2xl leading-7 text-sky-100">We explain our findings clearly and recommend the appropriate repair or next step based on the condition of your system.</p></div></div></section>
		<section className="mx-auto grid max-w-7xl gap-10 px-5 py-16 sm:px-8 sm:py-24 lg:grid-cols-2"><div><SectionTitle eyebrow="PREVENTATIVE CARE" title="Help Keep Your AC Ready for Florida Heat" text="Regular maintenance can help identify developing problems before they become major breakdowns. Top Notch AC maintenance includes inspection of major system components, airflow, drainage, electrical operation and cooling performance." /><div className="mt-7 grid grid-cols-2 gap-3">{ac.maintenance.map((item) => <p key={item} className="rounded-lg bg-sky-50 px-4 py-3 text-sm font-bold text-[#082544]">{item}</p>)}</div><div className="mt-7"><ActionButton href="/ac-maintenance">View AC Maintenance</ActionButton></div></div><div className="rounded-xl bg-[#eef7fb] p-7 sm:p-10"><Eyebrow>INSTALLATION & REPLACEMENT</Eyebrow><h2 className="mt-3 text-3xl font-black text-[#082544]">Need a New AC System?</h2><p className="mt-5 leading-7 text-slate-600">When repair is no longer the best option, Top Notch can help evaluate your existing equipment and provide replacement options based on the property, comfort needs, airflow and HVAC system requirements.</p><div className="mt-7 grid grid-cols-2 gap-3">{ac.installation.map((item) => <p key={item} className="rounded-lg bg-white px-4 py-3 text-sm font-bold text-[#082544]">{item}</p>)}</div><div className="mt-7"><ActionButton href="/ac-installation">Explore AC Installation</ActionButton></div></div></section>
		<section className="bg-sky-50 py-16 sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-8"><SectionTitle eyebrow="YOUR OPTIONS" title="Should You Repair or Replace Your AC?" text="Our technicians will explain the available options so you can make an informed decision." /><div className="mt-8 grid gap-5 md:grid-cols-2"><article className="rounded-xl border border-sky-200 bg-white p-7"><h3 className="text-2xl font-black text-[#082544]">Repair May Make Sense When</h3><ul className="mt-5 grid gap-3 text-sm font-bold text-slate-700">{["System is relatively newer", "Problem is isolated", "Repair cost is reasonable", "System otherwise performs well", "Major components remain in good condition"].map((item) => <li key={item}>+ {item}</li>)}</ul></article><article className="rounded-xl border border-slate-200 bg-white p-7"><h3 className="text-2xl font-black text-[#082544]">Replacement May Make Sense When</h3><ul className="mt-5 grid gap-3 text-sm font-bold text-slate-700">{["Equipment is aging", "Breakdowns are becoming frequent", "Major components have failed", "Repair costs are increasing", "Cooling performance is poor", "Efficiency has significantly declined"].map((item) => <li key={item}>+ {item}</li>)}</ul></article></div></div></section>
		<section className="bg-[#082544] py-16 text-white sm:py-24"><div className="mx-auto grid max-w-7xl gap-10 px-5 lg:grid-cols-2 lg:px-8"><div><Eyebrow light>LOCAL EXPERIENCE</Eyebrow><h2 className="mt-3 text-3xl font-black sm:text-4xl">AC Service Built for South Florida</h2><p className="mt-5 max-w-xl leading-7 text-sky-100">South Florida air conditioners work hard through long periods of heat and humidity. Heavy cooling demand, moisture, clogged drain lines, airflow problems and outdoor exposure can all affect system performance. Top Notch provides HVAC service focused on the conditions local homes and businesses experience every day.</p></div><VisualPlaceholder label="SOUTH FLORIDA HVAC SERVICE" className="min-h-64 rounded-xl border border-white/15" /></div></section>
		<section className="mx-auto max-w-7xl px-5 py-16 sm:px-8 sm:py-24"><SectionTitle eyebrow="WHO WE SERVE" title="AC Service for Homes & Businesses" /><div className="mt-8 grid gap-4 md:grid-cols-3">{[["Residential HVAC", "AC repair, replacement and maintenance for single-family homes and residential properties."], ["Condo AC Service", "HVAC diagnostics, repair and maintenance for condominium systems and accessible equipment."], ["Commercial HVAC", "Professional HVAC service for offices, businesses, retail locations and other commercial properties."]].map(([title, description]) => <article key={title} className="rounded-xl border border-slate-200 p-6"><h3 className="text-xl font-black text-[#082544]">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{description}</p></article>)}</div></section>
		<section className="bg-[#eef7fb] py-16 sm:py-24"><div className="mx-auto grid max-w-7xl gap-10 px-5 lg:grid-cols-[.8fr_1.2fr] lg:px-8"><div><SectionTitle eyebrow="WHY CHOOSE TOP NOTCH" title="Professional Service You Can Trust" /><blockquote className="mt-7 border-l-4 border-sky-500 pl-5 font-serif text-xl font-bold leading-snug text-[#082544]">&quot;{content.familyMessage}&quot;</blockquote></div><div className="grid gap-3 sm:grid-cols-2">{strengths.map((item) => <p key={item} className="rounded-lg bg-white p-4 text-sm font-bold text-[#082544] shadow-sm">+ {item === "Licensed & Insured" ? `${item} | ${content.license}` : item}</p>)}</div></div></section>
		<section className="mx-auto max-w-7xl px-5 py-16 sm:px-8 sm:py-24"><SectionTitle eyebrow="GOOGLE REVIEWS" title="Trusted by South Florida Homeowners" text="★★★★★ Real Google reviews will appear here after the verified review connection is configured." /><div className="mt-8 grid gap-4 md:grid-cols-3">{[1, 2, 3].map((item) => <article key={item} className="rounded-xl border border-slate-200 bg-slate-50 p-6"><p className="text-amber-400">★★★★★</p><p className="mt-5 text-sm font-bold text-slate-400">Verified review placeholder</p></article>)}</div><div className="mt-7"><ActionButton light>Read Our Google Reviews</ActionButton></div></section>
		<section className="border-y border-slate-200 bg-sky-50 py-16"><div className="mx-auto max-w-7xl px-5 sm:px-8"><SectionTitle eyebrow="RELATED SERVICES" title="More Than AC Service" text="Top Notch provides HVAC, duct and dryer vent services from one local company." /><div className="mt-7 grid gap-4 md:grid-cols-3">{[["Air Duct Cleaning", "/air-duct-cleaning"], ["Air Duct Repair & Installation", "/air-duct-cleaning"], ["Dryer Vent Cleaning", "/dryer-vent-cleaning"]].map(([title, href]) => <Link key={title} href={href} className="rounded-xl border border-slate-200 bg-white p-6 text-lg font-black text-[#082544] transition hover:border-sky-400 hover:text-sky-700">{title} +</Link>)}</div></div></section>
		<section className="mx-auto max-w-7xl px-5 py-16 sm:px-8 sm:py-24"><SectionTitle eyebrow="SERVICE AREAS" title="AC Service Throughout South Florida" /><div className="mt-7 flex flex-wrap gap-3">{priorityAreas.map((area) => <Link key={area.slug} href={`/service-areas/${area.slug}`} className="rounded-full border border-sky-200 bg-sky-50 px-4 py-2 text-sm font-bold text-[#082544] transition hover:border-sky-500">{area.name}</Link>)}</div><div className="mt-7"><ActionButton href="/service-areas">View All 40 Service Areas</ActionButton></div></section>
		<section className="bg-[#eef7fb] py-16 sm:py-24"><div className="mx-auto max-w-4xl px-5 sm:px-8"><SectionTitle eyebrow="AC FAQ" title="Answers to common AC service questions" /><div className="mt-7 grid gap-3">{ac.faqs.map((faq) => <details key={faq.question} className="rounded-lg border border-slate-200 bg-white p-5"><summary className="cursor-pointer font-bold text-[#082544]">{faq.question}</summary><p className="mt-4 leading-7 text-slate-600">{faq.answer}</p></details>)}</div></div></section>
		<section className="bg-[#082544] py-16 text-center text-white sm:py-22"><div className="mx-auto max-w-3xl px-5"><Eyebrow light>TOP NOTCH AC SERVICES</Eyebrow><h2 className="mt-4 text-3xl font-black sm:text-4xl">Need AC Service? Top Notch Is Ready to Help.</h2><p className="mt-5 text-sky-100">Whether your AC stopped cooling, needs maintenance or it is time for a replacement, contact Top Notch AC Services for professional HVAC service throughout South Florida.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><ActionButton phone>Call {content.phone}</ActionButton><ActionButton light>Book Service</ActionButton></div><p className="mt-7 font-bold text-sky-100">Licensed & Insured | {content.license}</p></div></section>
	</main><SiteFooter /></>;
}
