"use client";

import { useState } from "react";

const navItems = ["Home", "AC Services", "Air Duct Cleaning", "Dryer Vent Cleaning", "Maintenance", "Service Areas", "About", "Contact"];
const services = [
  { number: "01", title: "AC & HVAC Services", description: "Dependable comfort solutions for every season and every space.", items: ["AC Repair", "Emergency AC Repair", "AC Installation & Replacement", "AC Maintenance & Tune-Ups", "Air Handler Service"] },
  { number: "02", title: "Air Duct Cleaning", description: "Cleaner airflow for healthier, more comfortable interiors.", items: ["Residential Air Duct Cleaning", "Commercial Air Duct Cleaning", "Negative Pressure Cleaning", "Rotobrush Cleaning", "Air Duct Coating"] },
  { number: "03", title: "Dryer Vent Cleaning", description: "Professional cleaning that helps protect your property and equipment.", items: ["Dryer Vent Cleaning", "Clogged Dryer Vents", "D80 Dryer Warning Problems", "Dryer Vent Inspection", "Condo & Commercial Dryer Vent Cleaning"] },
];
const trustItems = ["Family-Owned & Operated", "Licensed & Insured", "5-Star Customer Service", "Residential & Commercial"];
const values = ["Honest recommendations", "Clear communication", "Professional workmanship", "Respect for the customer’s home", "Local South Florida service", "Family-owned and operated"];
const areas = ["Pompano Beach", "Fort Lauderdale", "Deerfield Beach", "Coconut Creek", "Coral Springs", "Margate", "Oakland Park", "Boca Raton"];

function Brand({ light = false }: { light?: boolean }) { return <a href="#home" className="flex items-center gap-3" aria-label="Top Notch AC Services home"><span className="flex size-11 items-center justify-center rounded-md bg-sky-500 text-lg font-black text-white">TN</span><span><span className={`block text-lg font-extrabold leading-none ${light ? "text-white" : "text-[#082544]"}`}>TOP NOTCH</span><span className={`mt-1 block text-[10px] font-bold tracking-[0.18em] ${light ? "text-sky-200" : "text-sky-700"}`}>AC SERVICES</span></span></a>; }
function Button({ children, inverse = false }: { children: React.ReactNode; inverse?: boolean }) { return <a href="#contact" className={`inline-flex min-h-12 items-center justify-center rounded-md px-6 text-sm font-bold transition ${inverse ? "border border-white/50 bg-white text-[#082544] hover:bg-sky-100" : "bg-sky-500 text-white hover:bg-sky-600"}`}>{children}</a>; }
function Intro({ eyebrow, title, text }: { eyebrow: string; title: string; text?: string }) { return <div className="max-w-2xl"><p className="text-xs font-extrabold tracking-[0.16em] text-sky-600">{eyebrow}</p><h2 className="mt-3 font-serif text-3xl font-bold leading-tight text-[#082544] sm:text-4xl">{title}</h2>{text && <p className="mt-4 text-base leading-7 text-slate-600">{text}</p>}</div>; }

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const link = (item: string) => `#${item.toLowerCase().replaceAll(" ", "-")}`;
  return <main id="home" className="overflow-hidden bg-white text-slate-900">
    <header className="relative z-20 border-b border-slate-200 bg-white"><div className="mx-auto flex min-h-20 max-w-7xl items-center justify-between gap-4 px-5 lg:px-8"><Brand /><nav className="hidden items-center gap-5 xl:flex" aria-label="Main navigation">{navItems.map((item) => <a key={item} href={link(item)} className="text-xs font-bold text-slate-600 hover:text-sky-600">{item}</a>)}</nav><div className="hidden items-center gap-3 md:flex"><a href="tel:7543660055" className="text-sm font-extrabold text-[#082544]">Call 754-366-0055</a><Button>Book Service</Button></div><button type="button" onClick={() => setMenuOpen(!menuOpen)} className="inline-flex size-11 items-center justify-center rounded-md border border-slate-300 text-[#082544] xl:hidden" aria-label="Toggle navigation" aria-expanded={menuOpen}><span className="space-y-1.5"><span className="block h-0.5 w-5 bg-current" /><span className="block h-0.5 w-5 bg-current" /><span className="block h-0.5 w-5 bg-current" /></span></button></div>{menuOpen && <nav className="absolute left-0 right-0 top-full border-y border-slate-200 bg-white px-5 py-5 shadow-lg xl:hidden" aria-label="Mobile navigation"><div className="mx-auto grid max-w-7xl gap-1">{navItems.map((item) => <a key={item} onClick={() => setMenuOpen(false)} href={link(item)} className="border-b border-slate-100 py-3 text-sm font-bold text-[#082544]">{item}</a>)}<div className="mt-4 grid gap-3 sm:grid-cols-2"><a href="tel:7543660055" className="inline-flex min-h-12 items-center justify-center rounded-md border border-[#082544] px-6 text-sm font-bold text-[#082544]">Call 754-366-0055</a><Button>Book Service</Button></div></div></nav>}</header>

    <section className="relative bg-[#082544] py-14 text-white sm:py-20 lg:py-28"><div className="absolute inset-0 opacity-25 [background-image:linear-gradient(90deg,transparent_49%,#66c7ef_50%,transparent_51%)] [background-size:70px_70px]" /><div className="relative mx-auto grid max-w-7xl items-center gap-12 px-5 lg:grid-cols-[1.05fr_.95fr] lg:px-8"><div><p className="text-xs font-extrabold tracking-[0.16em] text-sky-300">SOUTH FLORIDA COMFORT SPECIALISTS</p><h1 className="mt-5 max-w-3xl font-serif text-4xl font-bold leading-[1.06] sm:text-5xl lg:text-6xl">South Florida AC, Air Duct & Dryer Vent Experts</h1><p className="mt-6 max-w-2xl text-base leading-7 text-sky-50 sm:text-lg">Professional AC repair, installation, maintenance, air duct cleaning and dryer vent services for homes and businesses throughout Pompano Beach, Fort Lauderdale and surrounding South Florida communities.</p><p className="mt-6 border-l-2 border-sky-400 pl-4 text-sm font-bold text-sky-100">Licensed & Insured <span className="mx-2 text-sky-400">|</span> Florida HVAC License CAC1824888</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="tel:7543660055" className="inline-flex min-h-12 items-center justify-center rounded-md bg-sky-500 px-6 text-sm font-bold text-white hover:bg-sky-400">Call Now</a><Button inverse>Book Service</Button></div></div><div className="relative min-h-80 overflow-hidden rounded-lg border border-sky-300/30 bg-gradient-to-br from-sky-400 via-sky-600 to-[#0c3154] shadow-2xl"><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_25%,rgba(255,255,255,.5),transparent_20%),linear-gradient(135deg,transparent_45%,rgba(8,37,68,.35)_45%)]" /><div className="absolute bottom-6 left-6 max-w-56 border-l-2 border-white pl-4"><p className="text-xs font-extrabold tracking-[0.16em]">TOP NOTCH TEAM</p><p className="mt-2 text-sm leading-5 text-sky-50">Professional HVAC technician photo placeholder</p></div><div className="absolute -right-6 top-8 size-48 rounded-full border-[22px] border-white/20" /></div></div></section>
    <section className="bg-sky-50"><div className="mx-auto grid max-w-7xl divide-y divide-sky-200 px-5 sm:grid-cols-2 sm:divide-x sm:divide-y-0 lg:grid-cols-4 lg:px-8">{trustItems.map((item) => <div key={item} className="py-5 text-center text-sm font-extrabold text-[#082544]">{item}</div>)}</div></section>
    <section id="ac-services" className="mx-auto max-w-7xl px-5 py-16 sm:py-24 lg:px-8"><Intro eyebrow="OUR SERVICES" title="Complete Care for Cleaner, More Comfortable Spaces" text="From a quick repair to ongoing maintenance, our team brings careful work and clear answers to every call." /><div className="mt-10 grid gap-5 lg:grid-cols-3">{services.map((service) => <article key={service.title} className="group flex min-h-105 flex-col rounded-lg border border-slate-200 bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:border-sky-300 hover:shadow-lg"><p className="text-sm font-black text-sky-500">{service.number}</p><h3 className="mt-6 font-serif text-2xl font-bold text-[#082544]">{service.title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{service.description}</p><ul className="mt-6 space-y-3 border-t border-slate-100 pt-5">{service.items.map((item) => <li key={item} className="flex gap-3 text-sm text-slate-700"><span className="mt-2 size-1.5 shrink-0 rounded-full bg-sky-500" />{item}</li>)}</ul><a href="#contact" className="mt-auto pt-7 text-sm font-extrabold text-sky-700 group-hover:text-sky-500">Learn More <span aria-hidden="true">&gt;</span></a></article>)}</div></section>
    <section id="about" className="bg-[#eef7fb] py-16 sm:py-24"><div className="mx-auto grid max-w-7xl gap-12 px-5 lg:grid-cols-2 lg:px-8"><div className="rounded-lg bg-[#082544] p-7 text-white sm:p-10"><p className="text-xs font-extrabold tracking-[0.16em] text-sky-300">OUR PROMISE</p><blockquote className="mt-6 font-serif text-2xl font-bold leading-snug sm:text-3xl">“We are a proud family-owned and operated company built on faith, family and community. Top Notch is more than a business to us - it is part of the future we are building for our family and the communities we serve.”</blockquote><p className="mt-8 border-t border-white/20 pt-5 text-sm font-bold text-sky-100">Top Notch AC Services</p></div><div><Intro eyebrow="WHY CHOOSE TOP NOTCH" title="Professional Service You Can Trust" /><div className="mt-7 grid gap-3 sm:grid-cols-2">{values.map((value) => <div key={value} className="flex items-center gap-3 rounded-md bg-white px-4 py-4 text-sm font-bold text-[#082544] shadow-sm"><span className="flex size-6 items-center justify-center rounded-full bg-sky-100 text-sky-700">+</span>{value}</div>)}</div></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-16 sm:py-24 lg:px-8"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><Intro eyebrow="GOOGLE REVIEWS" title="Trusted by South Florida homeowners" text="Five-star service is the standard we work toward on every visit." /><div className="text-2xl tracking-[0.18em] text-amber-400" aria-label="Five out of five stars">*****</div></div><div className="mt-9 grid gap-5 md:grid-cols-3">{[1, 2, 3].map((review) => <article key={review} className="rounded-lg border border-slate-200 bg-slate-50 p-6"><div className="text-lg tracking-[0.14em] text-amber-400" aria-label="Placeholder five-star review">*****</div><p className="mt-5 text-sm font-bold text-slate-400">Placeholder customer review</p><p className="mt-3 text-sm leading-6 text-slate-500">Review content will be added from verified Google reviews.</p></article>)}</div><div className="mt-8"><a href="#contact" className="inline-flex min-h-12 items-center justify-center rounded-md border border-[#082544] px-6 text-sm font-bold text-[#082544] hover:bg-[#082544] hover:text-white">Read Our Google Reviews</a></div></section>
    <section id="service-areas" className="border-y border-slate-200 bg-white py-16 sm:py-24"><div className="mx-auto grid max-w-7xl gap-10 px-5 lg:grid-cols-[.8fr_1.2fr] lg:px-8"><Intro eyebrow="SERVICE AREAS" title="Proudly Serving South Florida" text="Local service for homes, businesses, condos and property managers across the region." /><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{areas.map((area) => <div key={area} className="flex min-h-20 items-center justify-center rounded-md border border-sky-100 bg-sky-50 px-3 text-center text-sm font-bold text-[#082544]">{area}</div>)}</div></div><div className="mx-auto mt-8 max-w-7xl px-5 lg:px-8"><a href="#contact" className="inline-flex min-h-12 items-center justify-center rounded-md border border-[#082544] px-6 text-sm font-bold text-[#082544] hover:bg-[#082544] hover:text-white">View All Service Areas</a></div></section>
    <section id="contact" className="bg-sky-500 py-16 text-center text-white sm:py-20"><div className="mx-auto max-w-3xl px-5"><p className="text-xs font-extrabold tracking-[0.16em] text-sky-950">READY WHEN YOU NEED US</p><h2 className="mt-4 font-serif text-3xl font-bold leading-tight sm:text-4xl">Need AC, Air Duct or Dryer Vent Service?</h2><p className="mt-5 text-base leading-7 text-sky-50">Top Notch is ready to help keep your home or business comfortable, clean and running properly.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><a href="tel:7543660055" className="inline-flex min-h-12 items-center justify-center rounded-md bg-[#082544] px-6 text-sm font-bold text-white hover:bg-[#103b63]">Call Now</a><Button inverse>Book Service</Button></div></div></section>
    <footer className="bg-[#061c32] py-12 text-sky-100"><div className="mx-auto grid max-w-7xl gap-10 px-5 sm:grid-cols-2 lg:grid-cols-4 lg:px-8"><div><Brand light /><p className="mt-5 text-sm leading-6 text-sky-200">Licensed & Insured<br />Florida HVAC License CAC1824888</p></div><div><h2 className="text-sm font-extrabold text-white">Explore</h2><div className="mt-4 grid gap-3 text-sm">{["Services", "Service Areas", "About", "Contact"].map((item) => <a key={item} href="#contact" className="hover:text-white">{item}</a>)}</div></div><div><h2 className="text-sm font-extrabold text-white">Contact</h2><div className="mt-4 grid gap-3 text-sm"><a href="tel:7543660055">Phone: 754-366-0055</a><a href="mailto:email@example.com">Email: [EMAIL]</a><span>Website: topnotchdryerventcleaning.com</span></div></div><div><h2 className="text-sm font-extrabold text-white">Follow Us</h2><div className="mt-4 flex gap-3"><a href="#contact" className="rounded border border-sky-500/50 px-3 py-2 text-xs font-bold hover:bg-sky-700">Facebook</a><a href="#contact" className="rounded border border-sky-500/50 px-3 py-2 text-xs font-bold hover:bg-sky-700">Instagram</a></div></div></div><div className="mx-auto mt-10 max-w-7xl border-t border-white/15 px-5 pt-6 text-xs text-sky-300 lg:px-8">Copyright 2026 Top Notch AC Services. All rights reserved.</div></footer>
  </main>;
}
