"use client";

import { ActionButton, SiteFooter, SiteHeader } from "@/components/site-shell";
import { useSiteContent } from "@/components/content-provider";
import { CardLink, Eyebrow, SectionTitle, VisualPlaceholder } from "@/components/home-sections";

const strengths = ["Family-Owned & Operated", "Licensed & Insured", "Honest Recommendations", "Professional Technicians", "Same-Day Service Available", "Residential & Commercial", "Quality Workmanship", "Local South Florida Company"];
const acServices = ["Emergency AC Repair", "AC Diagnostics", "AC Replacement", "Tune-Ups", "Coil Cleaning", "Air Handler Service", "Refrigerant Leak Detection", "Mini-Splits"];
const ductServices = ["Residential", "Commercial", "Negative Pressure Cleaning", "Rotobrush Cleaning", "Sanitizing", "Duct Coating", "Duct Sealing"];
const dryerServices = ["Dryer Vent Cleaning", "Clogged Dryer Vent", "Airflow Testing", "Condo Cleaning", "Commercial Cleaning", "Dryer Vent Repair"];

export default function Home() {
  const content = useSiteContent();
  return <><SiteHeader /><main className="overflow-hidden bg-white text-slate-900">
    <section className="relative bg-[#082544] py-16 text-white sm:py-24"><div className="absolute inset-0 opacity-15 [background-image:linear-gradient(90deg,transparent_49%,#7dd3fc_50%,transparent_51%)] [background-size:64px_64px]" /><div className="relative mx-auto grid max-w-7xl gap-12 px-5 lg:grid-cols-[1fr_.92fr] lg:items-center lg:px-8"><div><Eyebrow light>{content.hero.eyebrow}</Eyebrow><h1 className="mt-5 max-w-2xl text-4xl font-black leading-[1.05] sm:text-5xl lg:text-[3.45rem]">{content.hero.headline}</h1><p className="mt-6 max-w-2xl text-base leading-7 text-sky-50 sm:text-lg">{content.hero.description}</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><ActionButton phone>{content.ctas.primary}</ActionButton><ActionButton light>{content.ctas.secondary}</ActionButton></div><p className="mt-7 inline-flex items-center rounded-full border border-sky-300/60 bg-sky-950/30 px-4 py-2 text-base font-extrabold text-white">Licensed & Insured <span className="mx-2 text-sky-300">|</span> {content.license}</p></div><VisualPlaceholder label="TECHNICIAN + BRANDED VAN" className="min-h-86 rounded-xl border border-sky-300/30 shadow-2xl lg:min-h-115" /></div></section>
    <section className="bg-sky-50 py-15 sm:py-20"><div className="mx-auto max-w-7xl px-5 sm:px-8"><SectionTitle eyebrow="SERVICES WE OFFER" title="Comfort, clean air and dependable care." text="One local team for the systems and services that keep your property working properly." /><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{content.services.map((service) => <CardLink key={service.title} {...service} />)}</div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-16 sm:py-24 sm:px-8"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><SectionTitle eyebrow="WHY CHOOSE TOP NOTCH" title="Professional service you can trust." text="Clear answers, careful work and a local team that treats every home and business with respect." /><div className="grid gap-3 sm:grid-cols-2">{strengths.map((strength) => <div key={strength} className="flex items-center gap-3 rounded-lg border border-slate-200 p-4 text-sm font-bold text-[#082544]"><span className="grid size-6 place-items-center rounded-full bg-sky-100 text-sky-700">+</span>{strength}</div>)}</div></div></section>
    {content.sections.reviews && <section className="bg-[#eef7fb] py-16 sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><SectionTitle eyebrow="GOOGLE REVIEWS" title="Trusted by South Florida homeowners" text="Our review section is ready for verified customer feedback." /><div className="text-xl font-black tracking-[.16em] text-amber-400">★★★★★ <span className="ml-2 text-sm tracking-normal text-[#082544]">200+ Google Reviews</span></div></div><div className="mt-8 grid gap-4 md:grid-cols-3">{["Review placeholder 01", "Review placeholder 02", "Review placeholder 03"].map((review) => <article key={review} className="rounded-xl bg-white p-6 shadow-sm"><p className="text-amber-400">★★★★★</p><p className="mt-5 text-sm font-bold text-slate-400">{review}</p><p className="mt-3 text-sm leading-6 text-slate-500">Verified customer review content will be added here.</p></article>)}</div><div className="mt-7"><ActionButton href="/contact" light>Read Our Google Reviews</ActionButton></div></div></section>}
    {content.sections.acServices && <section className="mx-auto grid max-w-7xl gap-10 px-5 py-16 sm:py-24 lg:grid-cols-[.9fr_1.1fr] lg:px-8"><VisualPlaceholder label="AC SYSTEM SERVICE" className="min-h-80 rounded-xl" /><div><SectionTitle eyebrow="AC SERVICES" title="Keep your system ready for South Florida heat." text="From urgent repairs to planned replacements, we diagnose the right solution and explain the work clearly." /><div className="mt-7 grid grid-cols-2 gap-3">{acServices.map((item) => <div key={item} className="rounded-lg border border-slate-200 px-4 py-3 text-sm font-bold text-[#082544]">{item}</div>)}</div><div className="mt-7"><ActionButton href="/ac-services">Request AC Service</ActionButton></div></div></section>}
    {content.sections.airDuct && <section className="bg-[#082544] py-16 text-white sm:py-24"><div className="mx-auto grid max-w-7xl gap-10 px-5 lg:grid-cols-[1.1fr_.9fr] lg:px-8"><div><Eyebrow light>AIR DUCT CLEANING</Eyebrow><h2 className="mt-3 font-serif text-3xl font-bold leading-tight sm:text-4xl">Cleaner ducts. Better airflow.</h2><p className="mt-5 max-w-xl leading-7 text-sky-100">Professional equipment and a methodical approach for cleaner HVAC ductwork in homes and commercial properties.</p><div className="mt-7 grid grid-cols-2 gap-3">{ductServices.map((item) => <div key={item} className="border-b border-white/15 py-3 text-sm font-bold">{item}</div>)}</div><div className="mt-7"><ActionButton>Book Service</ActionButton></div></div><VisualPlaceholder label="ROTOBRUSH + NEGATIVE PRESSURE" className="min-h-80 rounded-xl border border-white/15" /></div></section>}
    {content.sections.dryerVent && <section className="mx-auto grid max-w-7xl gap-10 px-5 py-16 sm:py-24 lg:grid-cols-[.9fr_1.1fr] lg:px-8"><VisualPlaceholder label="DRYER VENT SERVICE" className="min-h-80 rounded-xl" /><div><SectionTitle eyebrow="DRYER VENT CLEANING" title="Dryer Showing D80? Clothes Taking Too Long to Dry?" text="A restricted vent can reduce drying performance and create a serious safety concern. We help restore safe, efficient airflow." /><div className="mt-7 grid grid-cols-2 gap-3">{dryerServices.map((item) => <div key={item} className="rounded-lg bg-sky-50 px-4 py-3 text-sm font-bold text-[#082544]">{item}</div>)}</div><div className="mt-7"><ActionButton>Book Dryer Vent Cleaning</ActionButton></div></div></section>}
    {content.sections.family && <section className="bg-sky-50 py-16 sm:py-24"><div className="mx-auto grid max-w-7xl gap-10 px-5 lg:grid-cols-2 lg:px-8"><div className="rounded-xl bg-[#082544] p-8 text-white sm:p-11"><Eyebrow light>FAMILY-OWNED & OPERATED</Eyebrow><blockquote className="mt-6 font-serif text-2xl font-bold leading-snug sm:text-3xl">&quot;{content.familyMessage}&quot;</blockquote><p className="mt-8 text-sm font-bold text-sky-200">{content.companyName}</p></div><VisualPlaceholder label="FAMILY TEAM OR BRANDED VAN" className="min-h-80 rounded-xl" /></div></section>}
    {content.sections.areas && <section className="mx-auto max-w-7xl px-5 py-16 sm:py-24 lg:px-8"><SectionTitle eyebrow="SERVICE AREAS" title="Serving the communities we call home." text="Reliable AC, air duct and dryer vent services throughout Broward County and nearby South Florida communities." /><div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{content.serviceAreas.map((area) => <div key={area} className="rounded-lg border border-sky-100 bg-sky-50 px-4 py-4 text-center text-sm font-bold text-[#082544]">{area}</div>)}</div></section>}
    <section className="border-y border-slate-200 bg-white"><div className="mx-auto grid max-w-7xl divide-y divide-slate-200 px-5 sm:grid-cols-3 sm:divide-x sm:divide-y-0 lg:px-8"><div className="py-6 text-center text-sm font-extrabold text-[#082544]">Licensed & Insured</div><div className="py-6 text-center text-sm font-extrabold text-[#082544]">Florida HVAC License {content.license}</div><div className="py-6 text-center text-sm font-extrabold text-[#082544]">★★★★★ Google Reviews</div></div></section>
    <section className="bg-sky-500 py-16 text-center text-white sm:py-22"><div className="mx-auto max-w-3xl px-5"><Eyebrow>READY WHEN YOU NEED US</Eyebrow><h2 className="mt-4 font-serif text-3xl font-bold sm:text-4xl">Need AC, Air Duct or Dryer Vent Service?</h2><p className="mt-5 text-sky-50">Call a local team that is ready to help keep your home or business comfortable, clean and running properly.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><ActionButton phone>Call Now</ActionButton><ActionButton light>Book Service</ActionButton></div></div></section>
  </main><SiteFooter /></>;
}
