"use client";

import { useState } from "react";

type Service = { title: string; tag: string; color: string };

const navigation = ["AC Services", "Air Duct Cleaning", "Dryer Vent Cleaning", "Maintenance", "Service Areas", "About", "Contact"];
const services: Service[] = [
  { title: "AC Repair", tag: "DIAGNOSTICS & REPAIRS", color: "from-sky-500 to-blue-800" },
  { title: "AC Installation", tag: "REPLACEMENT & NEW SYSTEMS", color: "from-blue-500 to-[#082544]" },
  { title: "AC Maintenance", tag: "TUNE-UPS & CARE", color: "from-cyan-500 to-blue-700" },
  { title: "Air Duct Cleaning", tag: "CLEANER INDOOR AIR", color: "from-sky-600 to-[#123f64]" },
  { title: "Dryer Vent Cleaning", tag: "SAFETY & AIRFLOW", color: "from-blue-700 to-[#061c32]" },
  { title: "Duct Repair & Installation", tag: "AIRFLOW SOLUTIONS", color: "from-[#176e9b] to-[#082544]" },
];
const strengths = ["Family-Owned & Operated", "Licensed & Insured", "Honest Recommendations", "Professional Technicians", "Same-Day Service Available", "Residential & Commercial", "Quality Workmanship", "Local South Florida Company"];
const acServices = ["Emergency AC Repair", "AC Diagnostics", "AC Replacement", "Tune-Ups", "Coil Cleaning", "Air Handler Service", "Refrigerant Leak Detection", "Mini-Splits"];
const ductServices = ["Residential", "Commercial", "Negative Pressure Cleaning", "Rotobrush Cleaning", "Sanitizing", "Duct Coating", "Duct Sealing"];
const dryerServices = ["Dryer Vent Cleaning", "Clogged Dryer Vent", "Airflow Testing", "Condo Cleaning", "Commercial Cleaning", "Dryer Vent Repair"];
const areas = ["Pompano Beach", "Fort Lauderdale", "Deerfield Beach", "Coconut Creek", "Coral Springs", "Margate", "Oakland Park", "Boca Raton", "Tamarac", "Plantation", "Hollywood", "Parkland"];

function Button({ children, light = false, phone = false }: { children: React.ReactNode; light?: boolean; phone?: boolean }) {
  return <a href={phone ? "tel:7543660055" : "#contact"} className={`inline-flex min-h-11 items-center justify-center rounded-full px-5 text-sm font-extrabold transition ${light ? "bg-white text-[#082544] hover:bg-sky-100" : "bg-sky-500 text-white hover:bg-sky-600"}`}>{children}</a>;
}
function Brand({ light = false }: { light?: boolean }) {
  return <a href="#home" className="flex items-center gap-2.5" aria-label="Top Notch AC Services home"><span className="grid size-10 place-items-center rounded-full bg-sky-500 text-sm font-black text-white">TN</span><span className={`text-base font-black leading-none ${light ? "text-white" : "text-[#082544]"}`}>TOP NOTCH<span className={`mt-1 block text-[9px] tracking-[.22em] ${light ? "text-sky-200" : "text-sky-700"}`}>AC SERVICES</span></span></a>;
}
function Eyebrow({ children, light = false }: { children: React.ReactNode; light?: boolean }) { return <p className={`text-xs font-extrabold tracking-[.16em] ${light ? "text-sky-200" : "text-sky-600"}`}>{children}</p>; }
function SectionTitle({ eyebrow, title, text }: { eyebrow: string; title: string; text?: string }) { return <div className="max-w-2xl"><Eyebrow>{eyebrow}</Eyebrow><h2 className="mt-3 font-serif text-3xl font-bold leading-tight text-[#082544] sm:text-4xl">{title}</h2>{text && <p className="mt-4 text-base leading-7 text-slate-600">{text}</p>}</div>; }
function VisualPlaceholder({ label, className = "" }: { label: string; className?: string }) { return <div className={`relative overflow-hidden bg-gradient-to-br from-sky-400 via-sky-600 to-[#082544] ${className}`}><div className="absolute inset-0 opacity-40 [background-image:linear-gradient(135deg,transparent_45%,white_45%,transparent_46%)]" /><div className="absolute bottom-5 left-5 border-l-2 border-white pl-3 text-xs font-bold tracking-[.14em] text-white">{label}<span className="mt-2 block text-[10px] font-medium tracking-normal text-sky-100">PHOTO PLACEHOLDER</span></div></div>; }

export default function Home() {
  const [open, setOpen] = useState(false);
  const href = (item: string) => `#${item.toLowerCase().replaceAll(" ", "-")}`;
  return <main id="home" className="overflow-hidden bg-white text-slate-900">
    <div className="bg-[#061c32] text-sky-100"><div className="mx-auto flex max-w-7xl items-center justify-between gap-3 px-5 py-2 text-xs sm:px-8"><span className="font-bold">Serving Broward + South Florida</span><div className="flex items-center gap-3"><a className="hidden font-bold sm:block" href="tel:7543660055">754-366-0055</a><a href="#contact" className="font-bold hover:text-white">Request Service</a><a href="#contact" className="rounded-full bg-sky-500 px-3 py-1.5 font-extrabold text-white">Book Service</a></div></div></div>
    <header className="sticky top-0 z-30 border-b border-slate-200 bg-white/95 backdrop-blur"><div className="mx-auto flex min-h-19 max-w-7xl items-center justify-between gap-4 px-5 sm:px-8"><Brand /><nav className="hidden items-center gap-5 lg:flex" aria-label="Main navigation">{navigation.map((item) => <a key={item} href={href(item)} className="text-xs font-bold text-slate-600 hover:text-sky-600">{item}</a>)}</nav><div className="hidden md:block"><Button>Book Service</Button></div><button type="button" onClick={() => setOpen(!open)} className="grid size-10 place-items-center rounded-full border border-slate-300 lg:hidden" aria-label="Toggle navigation" aria-expanded={open}><span className="space-y-1"><span className="block h-0.5 w-5 bg-[#082544]" /><span className="block h-0.5 w-5 bg-[#082544]" /><span className="block h-0.5 w-5 bg-[#082544]" /></span></button></div>{open && <nav className="absolute left-0 right-0 border-b border-slate-200 bg-white px-5 py-4 shadow-lg lg:hidden" aria-label="Mobile navigation">{navigation.map((item) => <a key={item} href={href(item)} onClick={() => setOpen(false)} className="block border-b border-slate-100 py-3 text-sm font-bold text-[#082544]">{item}</a>)}<div className="mt-4 grid grid-cols-2 gap-3"><Button phone>Call Now</Button><Button>Book Service</Button></div></nav>}</header>
    <section className="relative bg-[#082544] py-16 text-white sm:py-24"><div className="absolute inset-0 opacity-15 [background-image:linear-gradient(90deg,transparent_49%,#7dd3fc_50%,transparent_51%)] [background-size:64px_64px]" /><div className="relative mx-auto grid max-w-7xl gap-12 px-5 lg:grid-cols-[1fr_.92fr] lg:items-center lg:px-8"><div><Eyebrow light>SOUTH FLORIDA COMFORT SPECIALISTS</Eyebrow><h1 className="mt-5 max-w-3xl font-serif text-4xl font-bold leading-[1.06] sm:text-5xl lg:text-6xl">South Florida AC, Air Duct & Dryer Vent Experts</h1><p className="mt-6 max-w-2xl text-base leading-7 text-sky-50 sm:text-lg">Professional AC repair, installation, maintenance, air duct cleaning and dryer vent services for homes and businesses throughout South Florida.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Button phone>Call Now</Button><Button light>Request Service</Button></div><p className="mt-7 text-sm font-bold text-sky-100">Licensed & Insured <span className="mx-2 text-sky-400">|</span> CAC1824888</p></div><VisualPlaceholder label="TECHNICIAN + BRANDED VAN" className="min-h-86 rounded-xl border border-sky-300/30 shadow-2xl lg:min-h-115" /></div></section>
    <section className="bg-sky-50 py-15 sm:py-20"><div className="mx-auto max-w-7xl px-5 sm:px-8"><SectionTitle eyebrow="SERVICES WE OFFER" title="Comfort, clean air and dependable care." text="One local team for the systems and services that keep your property working properly." /><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{services.map((service) => <article key={service.title} className="group overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><VisualPlaceholder label={service.tag} className={`h-39 bg-gradient-to-br ${service.color}`} /><div className="flex items-center justify-between p-5"><h3 className="font-serif text-xl font-bold text-[#082544]">{service.title}</h3><a href="#contact" aria-label={`Learn more about ${service.title}`} className="grid size-9 place-items-center rounded-full bg-sky-100 text-sky-700 transition group-hover:bg-sky-500 group-hover:text-white">+</a></div></article>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-16 sm:py-24 sm:px-8"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><SectionTitle eyebrow="WHY CHOOSE TOP NOTCH" title="Professional service you can trust." text="Clear answers, careful work and a local team that treats every home and business with respect." /><div className="grid gap-3 sm:grid-cols-2">{strengths.map((strength) => <div key={strength} className="flex items-center gap-3 rounded-lg border border-slate-200 p-4 text-sm font-bold text-[#082544]"><span className="grid size-6 place-items-center rounded-full bg-sky-100 text-sky-700">+</span>{strength}</div>)}</div></div></section>
    <section className="bg-[#eef7fb] py-16 sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><SectionTitle eyebrow="GOOGLE REVIEWS" title="Trusted by South Florida homeowners" text="Our review section is ready for verified customer feedback." /><div className="text-xl font-black tracking-[.16em] text-amber-400">★★★★★ <span className="ml-2 text-sm tracking-normal text-[#082544]">200+ Google Reviews</span></div></div><div className="mt-8 grid gap-4 md:grid-cols-3">{["Review placeholder 01", "Review placeholder 02", "Review placeholder 03"].map((review) => <article key={review} className="rounded-xl bg-white p-6 shadow-sm"><p className="text-amber-400">★★★★★</p><p className="mt-5 text-sm font-bold text-slate-400">{review}</p><p className="mt-3 text-sm leading-6 text-slate-500">Verified customer review content will be added here.</p></article>)}</div><div className="mt-7"><a href="#contact" className="inline-flex rounded-full border border-[#082544] px-5 py-3 text-sm font-bold text-[#082544] hover:bg-[#082544] hover:text-white">Read Our Google Reviews</a></div></div></section>
    <section id="ac-services" className="mx-auto grid max-w-7xl gap-10 px-5 py-16 sm:py-24 lg:grid-cols-[.9fr_1.1fr] lg:px-8"><VisualPlaceholder label="AC SYSTEM SERVICE" className="min-h-80 rounded-xl" /><div><SectionTitle eyebrow="AC SERVICES" title="Keep your system ready for South Florida heat." text="From urgent repairs to planned replacements, we diagnose the right solution and explain the work clearly." /><div className="mt-7 grid grid-cols-2 gap-3">{acServices.map((item) => <div key={item} className="rounded-lg border border-slate-200 px-4 py-3 text-sm font-bold text-[#082544]">{item}</div>)}</div><div className="mt-7"><Button>Request AC Service</Button></div></div></section>
    <section id="air-duct-cleaning" className="bg-[#082544] py-16 text-white sm:py-24"><div className="mx-auto grid max-w-7xl gap-10 px-5 lg:grid-cols-[1.1fr_.9fr] lg:px-8"><div><Eyebrow light>AIR DUCT CLEANING</Eyebrow><h2 className="mt-3 font-serif text-3xl font-bold leading-tight sm:text-4xl">Cleaner ducts. Better airflow.</h2><p className="mt-5 max-w-xl leading-7 text-sky-100">Professional equipment and a methodical approach for cleaner HVAC ductwork in homes and commercial properties.</p><div className="mt-7 grid grid-cols-2 gap-3">{ductServices.map((item) => <div key={item} className="border-b border-white/15 py-3 text-sm font-bold">{item}</div>)}</div><div className="mt-7"><Button>Request Duct Cleaning</Button></div></div><VisualPlaceholder label="ROTOBRUSH + NEGATIVE PRESSURE" className="min-h-80 rounded-xl border border-white/15" /></div></section>
    <section id="dryer-vent-cleaning" className="mx-auto grid max-w-7xl gap-10 px-5 py-16 sm:py-24 lg:grid-cols-[.9fr_1.1fr] lg:px-8"><VisualPlaceholder label="DRYER VENT SERVICE" className="min-h-80 rounded-xl" /><div><SectionTitle eyebrow="DRYER VENT CLEANING" title="Dryer Showing D80? Clothes Taking Too Long to Dry?" text="A restricted vent can reduce drying performance and create a serious safety concern. We help restore safe, efficient airflow." /><div className="mt-7 grid grid-cols-2 gap-3">{dryerServices.map((item) => <div key={item} className="rounded-lg bg-sky-50 px-4 py-3 text-sm font-bold text-[#082544]">{item}</div>)}</div><div className="mt-7"><Button>Book Dryer Vent Cleaning</Button></div></div></section>
    <section id="about" className="bg-sky-50 py-16 sm:py-24"><div className="mx-auto grid max-w-7xl gap-10 px-5 lg:grid-cols-2 lg:px-8"><div className="rounded-xl bg-[#082544] p-8 text-white sm:p-11"><Eyebrow light>FAMILY-OWNED & OPERATED</Eyebrow><blockquote className="mt-6 font-serif text-2xl font-bold leading-snug sm:text-3xl">“We are a proud family-owned and operated company built on faith, family, and community. Top Notch is more than a business to us—it is part of the future we are building for our family and the communities we serve.”</blockquote><p className="mt-8 text-sm font-bold text-sky-200">Top Notch AC Services</p></div><VisualPlaceholder label="FAMILY TEAM OR BRANDED VAN" className="min-h-80 rounded-xl" /></div></section>
    <section id="service-areas" className="mx-auto max-w-7xl px-5 py-16 sm:py-24 lg:px-8"><SectionTitle eyebrow="SERVICE AREAS" title="Serving the communities we call home." text="Reliable AC, air duct and dryer vent services throughout Broward County and nearby South Florida communities." /><div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{areas.map((area) => <div key={area} className="rounded-lg border border-sky-100 bg-sky-50 px-4 py-4 text-center text-sm font-bold text-[#082544]">{area}</div>)}</div></section>
    <section className="border-y border-slate-200 bg-white"><div className="mx-auto grid max-w-7xl divide-y divide-slate-200 px-5 sm:grid-cols-3 sm:divide-x sm:divide-y-0 lg:px-8"><div className="py-6 text-center text-sm font-extrabold text-[#082544]">Licensed & Insured</div><div className="py-6 text-center text-sm font-extrabold text-[#082544]">Florida HVAC License CAC1824888</div><div className="py-6 text-center text-sm font-extrabold text-[#082544]">★★★★★ Google Reviews</div></div></section>
    <section id="contact" className="bg-sky-500 py-16 text-center text-white sm:py-22"><div className="mx-auto max-w-3xl px-5"><Eyebrow>READY WHEN YOU NEED US</Eyebrow><h2 className="mt-4 font-serif text-3xl font-bold sm:text-4xl">Need AC, Air Duct or Dryer Vent Service?</h2><p className="mt-5 text-sky-50">Call a local team that is ready to help keep your home or business comfortable, clean and running properly.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Button phone>Call Now</Button><Button light>Book Service</Button></div></div></section>
    <footer className="bg-[#061c32] py-12 text-sky-100"><div className="mx-auto grid max-w-7xl gap-9 px-5 sm:grid-cols-2 lg:grid-cols-4 lg:px-8"><div><Brand light /><p className="mt-5 text-sm leading-6 text-sky-200">Licensed & Insured<br />Florida HVAC License CAC1824888</p></div><div><h2 className="text-sm font-extrabold text-white">Services</h2><div className="mt-4 grid gap-2 text-sm"><a href="#ac-services">AC Services</a><a href="#air-duct-cleaning">Air Duct Cleaning</a><a href="#dryer-vent-cleaning">Dryer Vent Cleaning</a></div></div><div><h2 className="text-sm font-extrabold text-white">Company</h2><div className="mt-4 grid gap-2 text-sm"><a href="#service-areas">Service Areas</a><a href="#about">About</a><a href="#contact">Contact</a></div></div><div><h2 className="text-sm font-extrabold text-white">Contact</h2><div className="mt-4 grid gap-2 text-sm"><a href="tel:7543660055">754-366-0055</a><span>Email: [EMAIL]</span><span>topnotchdryerventcleaning.com</span></div></div></div></footer>
  </main>;
}
