import Image from "next/image";
import Link from "next/link";
import { ActionButton } from "@/components/site-shell";

export function Eyebrow({ children, light = false }: { children: React.ReactNode; light?: boolean }) { return <p className={`text-xs font-extrabold tracking-[.16em] ${light ? "text-sky-200" : "text-sky-600"}`}>{children}</p>; }
export function SectionTitle({ eyebrow, title, text }: { eyebrow: string; title: string; text?: string }) { return <div className="max-w-2xl"><Eyebrow>{eyebrow}</Eyebrow><h2 className="mt-3 font-serif text-3xl font-bold leading-tight text-[#082544] sm:text-4xl">{title}</h2>{text && <p className="mt-4 text-base leading-7 text-slate-600">{text}</p>}</div>; }
export function VisualImage({ label, src, className = "", priority = false }: { label: string; src: string; className?: string; priority?: boolean }) { return <div className={`relative overflow-hidden bg-[#082544] ${className}`}><Image src={src} alt={label} fill priority={priority} sizes="(min-width: 1024px) 50vw, 100vw" className="object-cover" /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-[#082544]/80 to-transparent px-5 pb-5 pt-12"><span className="border-l-2 border-white pl-3 text-xs font-bold tracking-[.14em] text-white">{label}</span></div></div>; }
export function VisualVideo({ label, src, poster, className = "" }: { label: string; src: string; poster: string; className?: string }) { return <div className={`relative overflow-hidden bg-[#082544] ${className}`}><video autoPlay muted loop playsInline preload="metadata" poster={poster} className="absolute inset-0 size-full object-cover"><source src={src} type="video/mp4" /></video><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-[#082544]/80 to-transparent px-5 pb-5 pt-12"><span className="border-l-2 border-white pl-3 text-xs font-bold tracking-[.14em] text-white">{label}</span></div></div>; }
export function CardLink({ href, title, tag, image }: { href: string; title: string; tag: string; image: string }) { return <Link href={href} className="group block overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm transition duration-200 hover:-translate-y-1 hover:border-sky-300 hover:shadow-lg focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-sky-500 active:translate-y-0"><VisualImage label={tag} src={image} className="h-39" /><div className="flex items-center justify-between p-5"><h3 className="font-serif text-xl font-bold text-[#082544]">{title}</h3><span className="grid size-9 place-items-center rounded-full bg-sky-100 text-sky-700 transition group-hover:bg-sky-500 group-hover:text-white">+</span></div></Link>; }
export { ActionButton };
