"use client";

import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { useSiteContent } from "@/components/content-provider";
import { ActionButton, SiteFooter, SiteHeader } from "@/components/site-shell";

const warnings = [["D80 or D90 Error Code", "These dryer alerts can indicate restricted exhaust airflow. A full vent-path inspection helps identify lint buildup or other restrictions."], ["Clothes Take Too Long to Dry", "A dryer taking too long to dry may be working against a clogged dryer vent, lint buildup, or a damaged exterior outlet."], ["Hot Dryer or Laundry Room", "Unusual heat around the dryer or laundry room can be a sign that the exhaust system needs professional attention."], ["Lint Around the Exterior Vent", "Lint collecting near the wall or roof outlet can indicate that the vent cap, flapper, or exhaust path should be inspected."], ["Burning Smell or Unsafe Dryer Operation", "If the dryer smells hot or appears unsafe, stop using it when safe to do so and arrange a professional inspection."]];
const process = [["1", "Inspect the full route", "Inspect the dryer connection, accessible vent route, and exterior outlet."], ["2", "Remove lint and debris", "Remove accessible lint buildup and debris using professional cleaning tools."], ["3", "Check the exit point", "Inspect the roof or wall vent cap, flapper, and visible exterior conditions."], ["4", "Reconnect and test airflow", "Reconnect the dryer and test airflow before the final review."]];
const services = ["Dryer Vent Cleaning", "Lint Removal", "Airflow Testing", "Dryer Reconnection", "Wall Vent Repair", "Roof Vent Inspection", "Roof/Wall Vent Flapper Repair", "Condo & Commercial Dryer Vent Service"];
const properties = [["Homes", "Thorough dryer vent cleaning for single-family homes, accessible laundry rooms, and exterior vent outlets."], ["Condos", "Condo dryer vent cleaning with attention to accessible shared routes, exterior access, and property requirements."], ["Businesses & Commercial Properties", "Commercial dryer vent cleaning for laundries, property managers, multi-unit properties, and business facilities."]];
const faqs = [["Why is my dryer taking multiple cycles to dry clothes?", "Dryers can take longer when airflow is restricted by lint buildup, a clogged dryer vent, a crushed transition duct, or an exterior vent cap that is not opening correctly. We inspect the full accessible path to identify the condition."], ["What does a D80 or D90 dryer code mean?", "A D80 or D90 dryer error code commonly indicates a significant exhaust airflow restriction. Professional dryer lint removal and vent inspection can help determine whether the issue is within the appliance connection, vent path, or exterior outlet."], ["How often should a dryer vent be cleaned?", "Cleaning frequency depends on dryer use, vent length, turns in the route, household size, and property conditions. Many properties benefit from periodic professional inspection and cleaning, especially when drying performance changes."], ["Do you clean dryer vents through the roof?", "When the dryer exhaust terminates at an accessible roof outlet, we can inspect the roof dryer vent condition and clean the accessible vent path as appropriate for the property and safe access."], ["Can you repair a damaged exterior dryer vent flap?", "Yes. We inspect wall and roof vent caps, flappers, and visible exterior conditions, then explain available wall dryer vent repair or dryer vent flapper repair options."], ["Do you provide dryer vent cleaning for condos and businesses?", "Yes. Top Notch provides condo dryer vent cleaning and commercial dryer vent cleaning for accessible systems, working with owners, managers, and property requirements."]];

function HeroImage() { const [failed, setFailed] = useState(false); return <div className="relative min-h-[360px] overflow-hidden bg-[#082544] sm:min-h-[420px] lg:min-h-full">{!failed && <Image src="/images/dryer-vent/dryer-vent-cleaning-hero.jpg" alt="Top Notch AC Services technician cleaning a dryer vent in Pompano Beach, Florida" fill priority sizes="(min-width: 1024px) 52vw, 100vw" onError={() => setFailed(true)} className="object-cover" />}{failed && <div className="absolute inset-0 flex items-end bg-[linear-gradient(135deg,#061c32,#0b4f7d,#0878b6)] p-8 text-white"><div><p className="text-xs font-black tracking-[.16em] text-sky-200">TOP NOTCH AC SERVICES</p><p className="mt-3 max-w-sm text-3xl font-black">Professional dryer vent cleaning</p><p className="mt-3 max-w-sm text-sm leading-6 text-sky-100">Add the dryer-vent-cleaning-hero.jpg image to feature your local service team.</p></div></div>}<div className="pointer-events-none absolute inset-0 bg-gradient-to-t from-[#061c32]/45 via-transparent" /></div>; }

export default function DryerVentCleaningPage() {
	const content = useSiteContent();
	const schema = { "@context": "https://schema.org", "@graph": [{ "@type": "LocalBusiness", name: content.companyName, telephone: content.phone, url: "https://topnotch-acservices.com", identifier: `Florida HVAC License ${content.license}`, areaServed: ["Pompano Beach", "Fort Lauderdale", "South Florida"] }, { "@type": "Service", name: "Dryer Vent Cleaning", serviceType: "dryer vent cleaning Pompano Beach", provider: { "@type": "LocalBusiness", name: content.companyName, telephone: content.phone }, areaServed: ["Pompano Beach", "Fort Lauderdale", "South Florida"], url: "https://topnotch-acservices.com/dryer-vent-cleaning" }, { "@type": "FAQPage", mainEntity: faqs.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) }] };
	return <><SiteHeader /><main className="overflow-hidden bg-white text-slate-900"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
		<section className="bg-[#edf8fc]"><div className="mx-auto grid max-w-7xl lg:grid-cols-[.94fr_1.06fr]"><div className="flex items-center px-5 py-14 sm:px-8 lg:py-20"><div className="max-w-xl"><p className="text-xs font-black tracking-[.16em] text-sky-700">DRYER VENT CLEANING • SOUTH FLORIDA</p><h1 className="mt-4 text-4xl font-black leading-tight text-[#082544] sm:text-5xl">Professional Dryer Vent Cleaning in Pompano Beach</h1><p className="mt-5 text-base leading-7 text-slate-700">Professional dryer vent cleaning, lint removal, airflow testing, and roof or wall vent repair for homes, condos, and businesses throughout South Florida.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><ActionButton>Book Dryer Vent Cleaning</ActionButton><ActionButton phone className="bg-[#082544] hover:bg-[#061c32]">Call {content.phone}</ActionButton></div><div className="mt-6 flex flex-wrap gap-3 text-xs font-bold text-slate-600"><span>Licensed & Insured</span><span>•</span><span>License {content.license}</span><span>•</span><span>Homes, Condos & Commercial Service</span></div></div></div><HeroImage /></div></section>
		<section className="border-b border-sky-100"><div className="mx-auto grid max-w-7xl grid-cols-2 divide-x divide-y divide-slate-200 px-5 sm:grid-cols-4 sm:divide-y-0 sm:px-8">{["Restore Dryer Airflow", "Inspect the Full Vent Path", "Repair Wall & Roof Vents", "Homes, Condos & Businesses"].map((item) => <div key={item} className="px-3 py-5 text-center text-sm font-black text-[#082544]">{item}</div>)}</div></section>
		<section className="mx-auto max-w-7xl px-5 py-14 sm:px-8 sm:py-18"><div className="mx-auto max-w-3xl text-center"><p className="text-xs font-black tracking-[.14em] text-sky-700">RESTRICTED DRYER VENT CONDITIONS</p><h2 className="mt-2 text-3xl font-black text-[#082544]">Do not ignore a restricted dryer vent.</h2><p className="mt-4 leading-7 text-slate-600">Lint buildup and restricted vent conditions can affect dryer performance. If there is a burning smell or the dryer appears unsafe, turn it off if safe to do so and call for service.</p></div><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{warnings.map(([title, text], index) => <article key={title} className="rounded-xl border border-slate-200 p-5 shadow-sm"><span className="grid size-9 place-items-center rounded-full bg-sky-50 text-sm font-black text-sky-700">0{index + 1}</span><h3 className="mt-4 text-base font-black leading-6 text-[#082544]">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></section>
		<section className="bg-[#082544] py-14 text-white sm:py-18"><div className="mx-auto max-w-7xl px-5 sm:px-8"><p className="text-xs font-black tracking-[.14em] text-sky-300">OUR PROCESS</p><h2 className="mt-2 text-3xl font-black">Clean the dryer vent from appliance to exit point.</h2><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{process.map(([number, title, text]) => <article key={number} className="rounded-xl border border-white/15 bg-white/8 p-6"><span className="grid size-11 place-items-center rounded-full bg-sky-400 text-sm font-black text-[#082544]">{number}</span><h3 className="mt-4 text-lg font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-sky-100">{text}</p></article>)}</div></div></section>
		<section className="mx-auto grid max-w-7xl gap-10 px-5 py-14 sm:px-8 sm:py-18 lg:grid-cols-[.88fr_1.12fr]"><div><p className="text-xs font-black tracking-[.14em] text-sky-700">DRYER EXHAUST SERVICES</p><h2 className="mt-2 text-3xl font-black text-[#082544]">One team for your dryer exhaust system.</h2><p className="mt-4 leading-7 text-slate-600">From dryer lint removal to wall dryer vent repair and roof dryer vent cleaning, we inspect the accessible system and explain the service that fits the condition.</p><div className="mt-7"><ActionButton>Book Dryer Vent Cleaning</ActionButton></div></div><div className="grid gap-3 sm:grid-cols-2">{services.map((service) => <div key={service} className="flex items-center gap-3 rounded-xl border border-slate-200 bg-slate-50 px-4 py-4 text-sm font-bold text-[#082544]"><span className="grid size-6 shrink-0 place-items-center rounded-full bg-sky-500 text-xs font-black text-white">+</span>{service}</div>)}</div></section>
		<section className="bg-sky-50 py-14 sm:py-18"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="text-center"><p className="text-xs font-black tracking-[.14em] text-sky-700">WHO WE SERVE</p><h2 className="mt-2 text-3xl font-black text-[#082544]">Dryer vent cleaning for every property type</h2></div><div className="mt-8 grid gap-4 md:grid-cols-3">{properties.map(([title, text]) => <article key={title} className="rounded-xl border border-sky-100 bg-white p-7 shadow-sm"><h3 className="text-xl font-black text-[#082544]">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></div></section>
		<section className="mx-auto max-w-7xl px-5 py-14 sm:px-8 sm:py-18"><div className="grid gap-8 rounded-2xl bg-[#061c32] p-7 text-white sm:p-10 lg:grid-cols-[1.15fr_.85fr] lg:items-center"><div><p className="text-xs font-black tracking-[.14em] text-sky-300">LOCAL SOUTH FLORIDA SERVICE</p><h2 className="mt-2 text-3xl font-black">Dryer vent cleaning for Pompano Beach, Fort Lauderdale & South Florida.</h2><p className="mt-4 max-w-2xl leading-7 text-sky-100">Top Notch provides dryer vent cleaning Pompano Beach residents and property managers can rely on, plus service throughout Fort Lauderdale and nearby South Florida communities.</p><div className="mt-5 flex flex-wrap gap-x-5 gap-y-3 text-sm font-black">{[["/service-areas", "View Service Areas"], ["/air-duct-cleaning", "Air Duct Cleaning"], ["/ac-services", "AC Services"], ["/contact", "Contact Top Notch"]].map(([href, label]) => <Link key={href} href={href} className="text-sky-300 hover:text-white">{label}</Link>)}</div></div><div className="rounded-xl bg-white/10 p-6"><p className="text-sm font-black text-sky-300">TOP NOTCH AC SERVICES</p><p className="mt-3 text-2xl font-black">Professional. Local. Family-Owned.</p><p className="mt-3 text-sm leading-6 text-sky-100">Licensed & Insured Florida HVAC Contractor • {content.license}</p></div></div></section>
		<section className="mx-auto max-w-7xl px-5 pb-14 sm:px-8 sm:pb-18"><div className="mx-auto max-w-3xl text-center"><p className="text-xs font-black tracking-[.14em] text-sky-700">DRYER VENT FAQ</p><h2 className="mt-2 text-3xl font-black text-[#082544]">Questions about dryer vent cleaning?</h2></div><div className="mt-8 grid gap-3 md:grid-cols-2">{faqs.map(([question, answer]) => <details key={question} className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm"><summary className="cursor-pointer list-none pr-6 text-sm font-black text-[#082544]"><span className="mr-3 text-xl font-normal text-sky-600">+</span>{question}</summary><p className="mt-3 pl-7 text-sm leading-6 text-slate-600">{answer}</p></details>)}</div></section>
		<section className="bg-[#edf8fc]"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-6 px-5 py-12 sm:px-8 lg:flex-row lg:items-center"><div><p className="text-xs font-black tracking-[.14em] text-sky-700">READY FOR BETTER AIRFLOW?</p><h2 className="mt-2 text-3xl font-black text-[#082544]">Make your dryer work better today.</h2><p className="mt-2 text-slate-600">Book professional dryer vent cleaning with Top Notch AC Services.</p></div><div className="flex flex-col gap-3 sm:flex-row"><ActionButton>Book Dryer Vent Cleaning</ActionButton><ActionButton phone className="bg-[#082544] hover:bg-[#061c32]">Call {content.phone}</ActionButton></div></div></section>
	</main><SiteFooter /></>;
}
